version: '3.9'

services:
  db:
    image: postgres:14
    restart: always
    ports:
      - '5435:5432'
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - web

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - '5050:80'
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - web

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: django-web
    command: >
      sh -c 'python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000'
    restart: always
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - web

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbit
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - .env
    networks:
      - web

  redis:
    image: redis:6-alpine
    container_name: redis
    restart: always
    ports:
      - '6383:6379'
    env_file:
      - .env
    networks:
      - web

  celery-worker:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: celery -A credit_transfer worker --loglevel=info
    container_name: celery-worker
    restart: always
    volumes:
      - celery_data:/celery/worker
    env_file:
      - .env
    depends_on:
      - web
      - rabbitmq
    networks:
      - web

  celery-beat:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: celery -A credit_transfer beat --loglevel=info
    container_name: celery-beat
    restart: always
    volumes:
      - celery_data:/celery/beat
    env_file:
      - .env
    depends_on:
      - web
      - rabbitmq
    networks:
      - web

  flower:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: celery -A credit_transfer flower
    container_name: flower
    restart: always
    volumes:
      - celery_data:/flower
    ports:
      - '5555:5555'
    env_file:
      - .env
    depends_on:
      - celery-worker
      - rabbitmq
    networks:
      - web

volumes:
  postgres_data:
  celery_data:

networks:
  web:
