# Generated by Django 4.2.26 on 2025-11-20 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charge',
            name='phone_number',
        ),
    ]
