# Generated by Django 4.2.9 on 2024-10-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='price',
            field=models.FloatField(default=1),
        ),
    ]
