# Generated by Django 4.2.9 on 2024-11-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='hash',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
